server:
  port: 0

spring:
  application:
    name: authentication-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

logging:
  pattern:
    console: =%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n

management:
  health:
    circuit-breakers:
      enabled: true
    web:
      exposure:
        include: prometheus
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

resilience4j:
  time-limiter:
    instances:
      user:
        timeout-duration: 3s
  retry:
    instances:
      user:
        max-attempts: 3
        wait-duration: 5s
  circuit-breaker:
    instances:
      user:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
