server:
  port: 0

spring:
  application:
    name: room-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Hotel
      username: username
      password: password
    web:
      pageable:
        default-page-size: 30
        size-parameter: size
        one-indexed-parameters: true
    rest:
      page-param-name: page
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

logging:
  pattern:
    console: =%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n

management:
  endpoints:
    web:
      exposure:
        include: prometheus

